### ISSUE TITLE
Patterns from styled-system is not exported on build using nuxt

### ISSUE THREAD

**Issue by procrates** [chakra-ui/panda#1257] opened 2023-08-22 18:55 UTC
### Description

When I deploy or build, I expect the exported functions of styled-system to be found in the template.

### Link to Reproduction

https://stackblitz.com/github/freefund-network/nuxt-panda-test

### Steps to reproduce

1. Run pnpm build
2. Wait for error.
3. Running multiple times may trigger other similar errors, but may also succeed.

### JS Framework

Nuxt 3

### Panda CSS Version

0.11.1

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I suspect that the script `panda codegen` is running multiple times during build and fails if the files dont exists. 

Thanks for providing such a beautiful module.

```
9:42:13 PM: Installing npm packages using pnpm version 8.6.7
9:42:13 PM: Lockfile is up to date, resolution step is skipped
9:42:13 PM: Progress: resolved 1, reused 0, downloaded 0, added 0
9:42:13 PM: Packages: +1115
9:42:13 PM: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
9:42:13 PM: Packages are hard linked from the content-addressable store to the virtual store.
9:42:13 PM:   Content-addressable store is at: /opt/build/.pnpm-store/v3
9:42:13 PM:   Virtual store is at:             node_modules/.pnpm
9:42:14 PM: Progress: resolved 1115, reused 0, downloaded 97, added 94
9:42:15 PM: Progress: resolved 1115, reused 0, downloaded 238, added 235
9:42:16 PM: Progress: resolved 1115, reused 0, downloaded 400, added 405
9:42:17 PM: Progress: resolved 1115, reused 0, downloaded 632, added 633
9:42:18 PM: Progress: resolved 1115, reused 0, downloaded 775, added 779
9:42:19 PM: Progress: resolved 1115, reused 0, downloaded 851, added 857
9:42:20 PM: Progress: resolved 1115, reused 0, downloaded 1058, added 1062
9:42:21 PM: .../node_modules/fast-folder-size postinstall$ node get-sysinternals-du.js
9:42:21 PM: .../node_modules/fast-folder-size postinstall: Done
9:42:21 PM: .../esbuild@0.17.19/node_modules/esbuild postinstall$ node install.js
9:42:21 PM: .../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
9:42:21 PM: .../esbuild@0.17.19/node_modules/esbuild postinstall: Done
9:42:21 PM: .../esbuild@0.18.20/node_modules/esbuild postinstall: Done
9:42:21 PM: Progress: resolved 1115, reused 0, downloaded 1109, added 1115, done
9:42:22 PM: devDependencies:
9:42:22 PM: + @nuxt/devtools 0.8.0
9:42:22 PM: + @pandacss/dev 0.11.1
9:42:22 PM: + @types/node 18.17.3
9:42:22 PM: + nuxt 3.6.5
9:42:22 PM: > nuxt-app@ postinstall /opt/build/repo
9:42:22 PM: > nuxt prepare
9:42:22 PM: [log] Nuxi 3.6.5
9:42:23 PM: [success] Types generated in .nuxt
9:42:23 PM: > nuxt-app@ prepare /opt/build/repo
9:42:23 PM: > panda codegen
9:42:24 PM: ✔️ `styled-system/css`: the css function to author styles
9:42:24 PM: ✔️ `styled-system/tokens`: the css variables and js function to query your tokens
9:42:24 PM: ✔️ `styled-system/patterns`: functions to implement apply common layout patterns
9:42:24 PM: Done in 11.5s
9:42:24 PM: npm packages installed using pnpm
9:42:25 PM: Install dependencies script success
9:42:25 PM: Starting build script
9:42:26 PM: Detected 1 framework(s)
9:42:26 PM: nuxt at version 3.6.5
9:42:26 PM: Section completed: initializing
9:42:27 PM: ​
9:42:27 PM: Netlify Build                                                 
9:42:27 PM: ────────────────────────────────────────────────────────────────
9:42:27 PM: ​
9:42:27 PM: ❯ Version
9:42:27 PM:   @netlify/build 29.20.6
9:42:27 PM: ​
9:42:27 PM: ❯ Flags
9:42:27 PM:   baseRelDir: true
9:42:27 PM:   buildId: 64e5016e547f1d12a42926ab
9:42:27 PM:   deployId: 64e5016e547f1d12a42926ad
9:42:27 PM: ​
9:42:27 PM: ❯ Current directory
9:42:27 PM:   /opt/build/repo
9:42:27 PM: ​
9:42:27 PM: ❯ Config file
9:42:27 PM:   No config file was defined: using default values.
9:42:27 PM: ​
9:42:27 PM: ❯ Context
9:42:27 PM:   production
9:42:27 PM: ​
9:42:27 PM: Build command from Netlify app                                
9:42:27 PM: ────────────────────────────────────────────────────────────────
9:42:27 PM: ​
9:42:27 PM: $ pnpm run build
9:42:27 PM: > nuxt-app@ build /opt/build/repo
9:42:27 PM: > nuxt build
9:42:27 PM: [log] Nuxi 3.6.5
9:42:27 PM: [log] Nuxt 3.6.5 with Nitro 2.5.2
9:42:29 PM: [info] Building client...
9:42:29 PM: [info] vite v4.3.9 building for production...
9:42:29 PM: [info] transforming...
9:42:34 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:42:30 PM: 🐼 info [hrtime] Extracted in (25.30ms)
9:42:31 PM: [info] ✓ 125 modules transformed.
9:42:31 PM: [info] rendering chunks...
9:42:31 PM: [info] computing gzip size...
9:42:31 PM: [info] .nuxt/dist/client/manifest.json                                  2.31 kB │ gzip:  0.38 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/error-500.cbe832a1.css                   1.95 kB │ gzip:  0.74 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/error-404.7b8544b4.css                   3.63 kB │ gzip:  1.12 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/_plugin-vue_export-helper.c27b6911.js    0.09 kB │ gzip:  0.10 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/error-500.54deffc5.js                    1.93 kB │ gzip:  1.02 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/error-404.0cfca11b.js                    6.58 kB │ gzip:  2.93 kB
9:42:31 PM: [info] .nuxt/dist/client/_nuxt/entry.639d0738.js                      112.76 kB │ gzip: 42.68 kB
9:42:31 PM: [info] ✓ built in 1.96s
9:42:31 PM: [success] Client built in 1963ms
9:42:31 PM: [info] Building server...
9:42:31 PM: [info] vite v4.3.9 building SSR bundle for production...
9:42:31 PM: [info] transforming...
9:42:32 PM: 🐼 info [hrtime] Extracted in (6.74ms)
9:42:32 PM: 🐼 info [hrtime] Extracted in (5.72ms)
9:42:32 PM: [info] ✓ 47 modules transformed.
9:42:32 PM: [info] ✓ built in 1.08s
9:42:32 PM: [error] vstack is not exported by styled-system/patterns/index.mjs, imported by app.vue?vue&type=script&setup=true&lang.ts.
9:42:32 PM: file: /opt/build/repo/app.vue?vue&type=script&setup=true&lang.ts:6:17
9:42:32 PM: 4:
9:42:32 PM: 5: import { css } from styled-system/css;
9:42:32 PM: 6: import { hstack, vstack } from styled-system/patterns;
9:42:32 PM:                     ^
9:42:32 PM: 7:
9:42:32 PM: 8: export default /*#__PURE__*/_defineComponent({
9:42:32 PM: [error] vstack is not exported by styled-system/patterns/index.mjs, imported by app.vue?vue&type=script&setup=true&lang.ts.
9:42:32 PM:   at error (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
9:42:32 PM:   at Module.error (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:13716:16)
9:42:32 PM:   at Module.traceVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:14146:29)
9:42:32 PM:   at ModuleScope.findVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:12589:39)
9:42:32 PM:   at FunctionScope.findVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
9:42:32 PM:   at ChildScope.findVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
9:42:32 PM:   at ReturnValueScope.findVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
9:42:32 PM:   at ChildScope.findVariable (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
9:42:32 PM:   at Identifier.bind (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:8309:40)
9:42:32 PM:   at CallExpression.bind (node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
9:42:32 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
9:42:32 PM: ​
9:42:32 PM: build.command failed                                        
9:42:32 PM: 
```

**Comment by astahmer** [comment] 2023-08-23 09:50
I tried this on your stackblitz link and couldn't reproduce:
❯ pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build


Σ Total size: 2.62 MB (643 kB gzip)
✔ You can preview this build using node .output/server/index.mjs                                           nitro 11:50:02

~/projects/rlmiogajo.github 1m 35s

**Comment by procrates** [comment] 2023-08-23 12:23
> I tried this on your stackblitz link and couldn't reproduce: ❯ pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build && pnpm build
> 
> Σ Total size: 2.62 MB (643 kB gzip) ✔ You can preview this build using node .output/server/index.mjs nitro 11:50:02
> 
> ~/projects/rlmiogajo.github 1m 35s

Strange, it works on stackblitz now, but not on local or vercel.

**Comment by procrates** [comment] 2023-08-23 12:25
> This started happening for us as well on version 0.11.1 with a qwik project, could not understand or reliably reproduce so we went back to 0.11.0 and problem disappeared

@moxival can confirm this works as well.

**Comment by segunadebayo** [comment] 2023-08-25 14:16
This happens intermittently on Vercel but works well on local and Stackblitz for me.

There's no plan of action on our end. Please permit me to close this out for now.

We'll re-open and investigate if it ever becomes a persistent bug for many users.

**Closed by segunadebayo** 2023-08-25 14:16 UTC
