### ISSUE TITLE
Patterns doesn't work in SvelteKit

### ISSUE THREAD

**Issue by dcheglakov** [chakra-ui/panda#761] opened 2023-06-20 20:46 UTC
### Description

When I tried to import `container` pattern to the main layout (or page), I expected to see generated classes for the container, but container classes `pos_relative max-w_8xl mx_auto px_4 md:px_6 lg:px_8` is not generated/extracted. 

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-bwygju?file=src%2Froutes%2F%2Blayout.svelte

### Steps to reproduce

1. Go to home page
2. Check the classes on the `main` element in the DevTools
3. Notice there are styles for the container classes. No Utilities Layer, only Base, Reset etc
4. Try to use any pattern all of them will be without styles

### JS Framework

SvelteKit (TS)

### Panda CSS Version

0.3.2

### Browser

Google Chrome 114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2023-06-21 09:38
@astahmer filed a PR for improved Svelte and Vue support. Should be fixed in the next release

If the issue persists after the release, I'll re-open this issue.

**Closed by segunadebayo** 2023-06-21 09:38 UTC

**Comment by anubra266** [comment] 2024-02-18 06:20
@tokenvolt The issue is panda doesn't parse jsx styles when `jsxFramework` option is not set in the config. Was designed this way to reduce the amount of work panda does and artifacts generated if the user doesn't ned jsx.

Svelte is not an option in that config key yet, but for your usecase; in the mean time, while we think of the best way to go around this, you can just pass any framework there for now. E.g.:
 `jsxFramework: "react"` 
just to tell Panda that it should parse styles in your JSX.

**Comment by tokenvolt** [comment] 2024-02-18 11:40
@anubra266 Thank you! I think it is worth to be added in the docs section for Svelte integration.

**Comment by anubra266** [comment] 2024-02-19 21:54
@tokenvolt In the latest version, you can now do `jsxFramework: 'svelte'`
