### ISSUE TITLE
Hot reload on styled component doesn't work (VueJS)

### ISSUE THREAD

**Issue by Vincent-HD** [chakra-ui/panda#1427] opened 2023-09-26 19:29 UTC
### Description

When I edit a styled component's props, and hit save, HMR triggers, styles are being extracted but the DOM is not being updated correctly, note that `css({})` updates the element correctly

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-hmuvma?file=src%2FApp.vue

### Steps to reproduce

Use a styled component, patterns or styled directly:

```html
<styled.div bgColor="amber.300">Hot reload test with styled</styled.div>
<Flex bgColor="pink.300">Hot reload test with Flex</Flex>
```

Change bgColor property for example to `x.500`
The color didn't change after HMR triggers
Note that manually reloading the page works as expected

### JS Framework

Vue (TS)

### Panda CSS Version

0.15.1

### Browser

Chrome 115

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Note that updating classes inside native HTML element correctly updates the class property in the DOM after HMR
![vivaldi_EvCVNPwQyU](https://github.com/chakra-ui/panda/assets/61592570/7bdbe0bf-557e-4293-84ea-ca53dc074e15)

**Comment by segunadebayo** [comment] 2023-09-27 19:01
After investigating this, I found that it's a duplicate of https://github.com/chakra-ui/panda/issues/1426.

Still relating to HMR and the cache.

**Closed by segunadebayo** 2023-09-27 19:01 UTC
