### ISSUE TITLE
The nested colors do not get applied in statically generated colorPalette

### ISSUE THREAD

**Issue by soroush96** [chakra-ui/panda#2006] opened 2024-01-15 03:38 UTC
### Description

When I use `colorPalette` with `semanticTokens` the nested value is missing when we try to generate them statically. This behaviour is different from other properties like backgroundColor, etc...

in the attached example the two in the first row use `colorPalette` while the two in the second row use `backgroundColor` property.

I expect to see styles generated from `colorPalette` property work the same as `backgroundColor` property.

![image](https://github.com/chakra-ui/panda/assets/54735152/1862de87-ef74-4bc1-a628-00ff77f09844)

### Link to Reproduction

https://play.panda-css.com/0-ooj8ktMh

### Steps to reproduce

1. Define semantic colors with `semanticTokens` that include nested colors
```
  theme: {
    extend: {},
    semanticTokens: {
      colors: defineSemanticTokens.colors({
        primary: {
          DEFAULT: { value: 'green' },
          container: {
            value: 'yellow',
          },
        },
      }),
    },
  },
```
2. Define colorPalette property in `staticCss` with semantic colors:
```
      staticCss: {
        css: [
          {
            properties: {
              colorPalette: ['primary', 'primary.container'],
            },
          },
        ],
      },
```

### Panda CSS Version

0.27.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment] 2024-01-19 19:26
Hi @soroush96,

This is by design, not a bug. When using the `colorPalette` property, you must set its value to the nested color key (in this case, 'primary').

The point of colorPalette is this; 

You set the nested color key via

```js
css({ bg: 'colorPalette.container' })
```

then set the colorPalette value to any color group that include the "container" property

```js
css({ colorPalette: 'primary', bg: 'colorPalette.container' })
```

Color Palette cannot be assigned to specific color value "primary.yellow", but a group of colors "primary"

Hope this make sense?

Cheers.

**Closed by segunadebayo** 2024-01-19 19:26 UTC
