### ISSUE TITLE
Non-semantic tokens are no longer expanded

### ISSUE THREAD

**Issue by Pinpickle** [chakra-ui/panda#1399] opened 2023-09-22 11:10 UTC
### Description

I just upgraded from Panda 0.13.0 to 0.15.1

I have some colour tokens defined like this:

```ts
const colors = defineTokens.colors({
  "purple": {
    DEFAULT: { value: "{colors.purple.100}" },
    100: { value: "#A0F" },
  },
});
```

Then, I'd use the hex value from the `token` function:

```ts
import { token } from "styled-system/tokens";

console.log(token('colors.purple'));
```

**Expected behaviour**: the console prints the hex value (`#A0F`)
**Actual behaviour**: the console prints a variable reference to `colors.purple.100` (`var(--colors-purple-100)`)

I think this was caused by #1382 which re-uses variables in semantic tokens. I don't mind that behaviour, but I didn't expect the change to also apply to non-semantic tokens.

NB: 0.15.0 doesn't have this issue

### Link to Reproduction

https://play.panda-css.com/-KEWA6_ecE

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React (TS)

### Panda CSS Version

0.15.1

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by isBatak** [comment] 2023-09-24 08:42
Hi @Pinpickle 👋, thank you for the issue report and the reproduction, we are working on the solution.
Could you give us the real world example when do you need a raw hex value? I'm trying to understand why can't you use `var(--colors-purple-100)`.

**Comment by Pinpickle** [comment] 2023-09-25 10:14
Sure thing @isBatak!

Two use-cases I have that come to mind are:

1. using the tokens in non-DOM areas where CSS variables aren't expanded (e.g. drawing on `canvas`)
2. doing a reverse-lookup of a hex code to go back to a token name. This is useful for dynamically trying to find the next darkest or lightest colour in a colour scale. This could definitely be worked around but in combination with (1) it's pretty tricky.

**Comment by isBatak** [comment] 2023-09-25 12:02
@Pinpickle thx for the use-cases.

> 1. using the tokens in non-DOM areas where CSS variables aren't expanded (e.g. drawing on canvas)

What if you have this situation
```
export default defineConfig({
  theme: {
    tokens: {
      colors: {
        purple: { 
          DEFAULT: { value: "{colors.purple.100}" },
          100: { value: "#A0F" },
        },
      }
    },
    semanticTokens: {
      colors: {
        primary: { value: '{colors.purple}' },
      }
    }
  }
})
```
What are the chances someone would need to use `token('colors.primary')` inside `canvas` context? 
Because in this case we are back on the root problem because `token` will return `var(--colors-primary)`.

Semantic tokens can also be conditional:
```
semanticTokens: {
      colors: {
        primary: {
          value: { base: '{colors.purple.400}', _dark: '{colors.primary.200}' }
        },
     },
},
```

We can add this opinionated rule and call it a day
> Within the “tokens” group, if you reference another token that is a non-semantic token, we’ll use the raw value instead of css var. In other cases, we use css vars.

**Comment by segunadebayo** [comment] 2023-09-26 15:20
From the look of things, there are no further actions we need to take.

> I recommend sticking with the rule @isBatak stated above

**Comment by isBatak** [comment] 2023-09-26 18:29
yeah... @segunadebayo I'm still working on this issue 😅

**Comment by isBatak** [comment] 2023-10-03 22:39
@Pinpickle could you check if your issues are resolved in this playground https://panda-playground-git-fix-expand-non-semantic-t-b5a874-chakra-ui.vercel.app/

**Comment by Pinpickle** [comment] 2023-10-09 11:05
@isBatak thanks for setting up the playground (and sorry for the delay). I can confirm tokens are expanding how I'd expect them to!

**Comment by segunadebayo** [comment] 2023-10-27 19:41
Closing this based on https://github.com/chakra-ui/panda/pull/1473#issuecomment-1783417665

It might not be as convenient, but please bear with us as we further improve Panda.

**Closed by segunadebayo** 2023-10-27 19:41 UTC
Labels: bug

**Comment by Pinpickle** [comment] 2023-11-14 23:51
@segunadebayo that's a shame but I understand. Sometimes it's important to say "no" in ambitious projects like these. I'll find another way (of which there are many) to achieve what I'm trying to do. Thanks for explaining your reasoning.
