### ISSUE TITLE
Cannot install @pandacss/dev with npm

### ISSUE THREAD

**Issue by theMosaad** [chakra-ui/panda#723] opened 2023-06-18 20:46 UTC
### Description

When I run
```
npm install -D @pandacss/dev
```

I get the following error
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

### Link to Reproduction

https://stackblitz.com/edit/remix-run-remix-nsqctn?file=package.json

### Steps to reproduce

Follow the [Getting Started with Remix](https://panda-css.com/docs/getting-started/remix) using npm instead of pnpm

### JS Framework

Remix (TS)

### Panda CSS Version

0.3.1

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Node version: v18.16.0
NPM version: 9.6.7

It was installed successfully with a [fresh Remix App on Stackblitz](https://stackblitz.com/edit/remix-run-remix-nsqctn?file=package.json) so i matched its Node and npm versions and tried again but got the same error.

**Comment by segunadebayo** [comment] 2023-06-18 21:10
Duplicate of https://github.com/chakra-ui/panda/issues/705

Pushed a fix for this. We'll release an update shortly

**Closed by segunadebayo** 2023-06-18 21:10 UTC
