### ISSUE TITLE
Type error: `defineTextStyles` is not compatible anymore with `Theme['textStyles']`

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/panda#1262] opened 2023-08-24 11:29 UTC
### Description

After updating to the latest version, I noticed that I got a typescript error.

This error exactly: 
```
Type 'import("/Users/omarkhatib/Documents/GitHub/pandacss-test/styled-system/types/composition").TextStyles' is not assignable to type 'import("/Users/omarkhatib/Documents/GitHub/pandacss-test/node_modules/.pnpm/@pandacss+types@0.8.0/node_modules/@pandacss/types/dist/composition").TextStyles'.
  'string' index signatures are incompatible.
    Type 'import("/Users/omarkhatib/Documents/GitHub/pandacss-test/styled-system/types/composition").Token<import("/Users/omarkhatib/Documents/GitHub/pandacss-test/styled-system/types/composition").TextStyle> | import("/Users/omarkhatib/Documents/GitHub/pandacss-test/styled-system/types/composition").Recursive<...>' is not assignable to type 'import("/Users/omarkhatib/Documents/GitHub/pandacss-test/node_modules/.pnpm/@pandacss+types@0.8.0/node_modules/@pandacss/types/dist/composition").Token<import("/Users/omarkhatib/Documents/GitHub/pandacss-test/node_modules/.pnpm/@pandacss+types@0.8.0/node_modules/@pandacss/types/dist/composition").TextStyle> | import...'.
      Type 'Token<TextStyle>' is not assignable to type 'Token<TextStyle> | Recursive<Token<TextStyle>>'.
        Type 'Token<TextStyle>' is not assignable to type 'Recursive<Token<TextStyle>>'.
          Property 'value' is incompatible with index signature.
            Type 'TextStyle' is not assignable to type 'Token<TextStyle> | Recursive<Token<TextStyle>>'.
              Type 'TextStyle' is not assignable to type 'Recursive<Token<TextStyle>>'.
                Property 'fontSize' is incompatible with index signature.
                  Type 'FontSizeToken | FontSize<String | Number> | NonNullable<FontSize<String | Number> | undefined>[] | (FontSizeToken | ... 3 more ... | undefined)[] | { ...; }' is not assignable to type 'Token<TextStyle> | Recursive<Token<TextStyle>>'.
                    Type 'string' is not assignable to type 'Token<TextStyle> | Recursive<Token<TextStyle>>'.ts(2322)

```

The problem is that I define the `textStyles` using `defineTextStyles` from panda and it seems the function is not correctly typed anymore

a workaround that fix the problem for now is to use `satisfies Theme['textStyles']` instead on the function

### Link to Reproduction

https://github.com/omarkhatibco/pandacss-test

### Steps to reproduce

please clone the repository and check `panda.config.cjs` file

### JS Framework

React (TS)

### Panda CSS Version

0.12.0

### Browser

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by fseglard** [comment] 2023-08-24 21:46
I have the exact same problem with the `defineLayerStyles` function.

**Comment by segunadebayo** [comment] 2023-08-25 15:58
Good catch @omarkhatibco and @fseglard.

I must be related to the fact that we recently re-exported types from `@pandacss/types` and TS is not happy.

I found the root cause and pushed a fix for this.

If the issue persists after upgrading, I'll re-open it.

**Closed by segunadebayo** 2023-08-25 15:58 UTC

**Comment by omarkhatibco** [comment] 2023-08-25 17:09
Thank you, I will infor you once the new version is published

**Comment by pkrawc** [comment] 2023-08-25 17:12
I'm still experiencing (a slightly different) type issue with `defineLayerStyles`

```
No overload matches this call.
  Overload 2 of 2, '(definition: LayerStyles): LayerStyles', gave the following error.
    Type 'string' is not assignable to type 'Token<LayerStyle> | Recursive<Token<LayerStyle>>'.
  Overload 2 of 2, '(definition: LayerStyles): LayerStyles', gave the following error.
    Type 'string' is not assignable to type 'Token<LayerStyle> | Recursive<Token<LayerStyle>>'.
  Overload 2 of 2, '(definition: LayerStyles): LayerStyles', gave the following error.
    Type 'string' is not assignable to type 'Token<LayerStyle> | Recursive<Token<LayerStyle>>'
```

**Comment by omarkhatibco** [comment] 2023-08-25 17:40
@pkrawc I think it’s not published yet

**Comment by pkrawc** [comment] 2023-08-25 18:01
Seems the proposed fix was release a couple hours ago, no?

https://github.com/chakra-ui/panda/commit/a969011091b95c74fe7af956ce2a183a82adc422

**Comment by segunadebayo** [comment] 2023-08-25 19:56
It’s not released yet. We should get it out by tomorrow
