### ISSUE TITLE
Invalid attribute name: `&>img, &>video`

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/panda#744] opened 2023-06-19 22:50 UTC
### Description

I'm trying to use `aspectRatio` function, the problem is that the engine does not recognize the custom selectors such as `&>img, &>video` or `&>*`
it works fine if I define this inside the function but not inside the patterns.

inside storybook it even did not recognize the _before condition.

### Link to Reproduction

https://codesandbox.io/p/github/omarkhatibco/pandacss-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj3g2y4k000b3b6nca8rhglx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj3g2y4k000d3b6npw8t91vd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clj3g2y4k000b3b6nca8rhglx%2522%253A%257B%2522id%2522%253A%2522clj3g2y4k000b3b6nca8rhglx%2522%252C%2522activeTabId%2522%253A%2522clj3g32dn007q3b6n9vpczkud%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clj3g2y4k000a3b6ne53qyvb8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.node.json%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpatterns.ts%2522%252C%2522id%2522%253A%2522clj3g32dn007q3b6n9vpczkud%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clj3g2y4k000d3b6npw8t91vd%2522%253A%257B%2522id%2522%253A%2522clj3g2y4k000d3b6npw8t91vd%2522%252C%2522activeTabId%2522%253A%2522clj3g55w900na3b6n5jyzb1zg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clj3g527g00h73b6nc0l440p1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clj3g55w900na3b6n5jyzb1zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Open codesandbox and check the console, and the classes and you would see there are no calsses generated for the video or img 

### JS Framework

React (TS)

### Panda CSS Version

0.3.2

### Browser

Latest Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

you could activete the custom pattern and check with the `&>*` selector

**Comment by omarkhatibco** [comment] 2023-06-20 00:40
I just noticed that the `ratio` prop is not working as well

**Comment by segunadebayo** [comment] 2023-06-20 13:59
Again. Good catch @omarkhatibco 

Love how you dig into the issue to show where the problem is. Helps us resolve issues much faster.

I've pushed a fix for this.

**Closed by segunadebayo** 2023-06-20 13:59 UTC
